version: '3.8'

services:
  
  postgresql:
    container_name: postgres
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: postgresql0000
      POSTGRES_DB: tuitter-db
    ports:
      - 5432:5432
    volumes:
      - ./data-docker/postgresql:/var/lib/postgresql/data

  pgadmin4:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ovidioromero66@gmail.com 
      PGADMIN_DEFAULT_PASSWORD: o@Rg940703
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 8080:80
    volumes:
      - ./data-docker/pgadmin4:/var/lib/pgadmin
    depends_on:
      - postgresql
